// Code generated by "stringer -type=DiagnosticLevel"; DO NOT EDIT.

package racket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DlInfo-0]
	_ = x[DlWarn-1]
	_ = x[DlFatal-2]
}

const _DiagnosticLevel_name = "DlInfoDlWarnDlFatal"

var _DiagnosticLevel_index = [...]uint8{0, 6, 12, 19}

func (i DiagnosticLevel) String() string {
	if i < 0 || i >= DiagnosticLevel(len(_DiagnosticLevel_index)-1) {
		return "DiagnosticLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiagnosticLevel_name[_DiagnosticLevel_index[i]:_DiagnosticLevel_index[i+1]]
}
