// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package racket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TtQuote-0]
	_ = x[TtPound-1]
	_ = x[TtSemi-2]
	_ = x[TtEscape-3]
	_ = x[TtPipe-4]
	_ = x[TtParenL-5]
	_ = x[TtParenR-6]
	_ = x[TtBracketL-7]
	_ = x[TtBracketR-8]
	_ = x[TtBraceL-9]
	_ = x[TtBraceR-10]
	_ = x[TtIndent-11]
	_ = x[TtLf-12]
	_ = x[TtString-13]
	_ = x[TtOther-14]
}

const _TokenType_name = "TtQuoteTtPoundTtSemiTtEscapeTtPipeTtParenLTtParenRTtBracketLTtBracketRTtBraceLTtBraceRTtIndentTtLfTtStringTtOther"

var _TokenType_index = [...]uint8{0, 7, 14, 20, 28, 34, 42, 50, 60, 70, 78, 86, 94, 98, 106, 113}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
