## README
#! case insensitive
#! token mode (whitespace omitted between tokens)
#! ordered unions (<a> | <b> is different than <b> | <a>)

<a> ::= "a" | "an"
<identifer> ::= builtin

<comment> ::= (<meaningful> | <garbage>)*
<garbage> ::= <anything> "\n"
<meaningful> ::=
   | <template>
   | <declaration>
   | <annotation>

<template> ::= "template" ":"? "\n" <declaration>

<declaration> ::=
   <a> (<declaration-generic> | <identifier>) "is" (<sum-type> | <alias>)

<declaration-generic> ::=
   | "(" <identifer> <identifer>+ ")"
   | "[" <identifer> <identifer>+ ")"
<sum-type> ::= "one" "of" <sum-type-element> <sum-type-element>+
<sum-type-term> ::= "\n" "-" <type>
<alias> ::= <a>? <type>

<annotation> ::= <identifer> ":" <function-type-inside> | <type>

<type> ::=
   | <quote>
   | <function-type>
   | <list-type>
   | <identifier>
   | <string>
<quote> ::= "'" <type>
<function-type> ::= "[" <function-type-inside> "]"
<function-inside> ::= <function-generic>? <type>+ "->" <type>
<function-generic> ::= "{" <identifier>+ "}"
<list-type> ::=
   | "(" <type>* ")"
   | "[" <type>* "]"
