## README
#! case insensitive
#! token mode (whitespace omitted between tokens)
#! ordered unions (<a> | <b> is different than <b> | <a>)

<a> ::= "a" | "an"
<word> ::= assumed

<comment> ::= (<meaningful> | <garbage>)*
<garbage> ::= <anything> "\n"
<meaningful> ::=
   | <template>
   | <declaration>
   | <annotation>

<template> ::= "template" ":"? "\n" <declaration>

<declaration> ::= <a> <declaration-target> "is" (<sum-type-rhs> | <alias-rhs>)
<declaration-target> ::=
   | <declaration-generic>
   | <word>
<declaration-generic> ::=
   | "(" <word> <word>+ ")"
   | "[" <word> <word>+ ")"
<sum-type-rhs> ::= "one" "of" <sum-type-element> <sum-type-element>+
<sum-type-element> ::= "\n" "-" <type>
<alias-rhs> ::= <a>? <type>

<annotation> ::= <word> ":" <function-type-inside> | <type>

<type> ::=
   | <function-type>
   | <list-type>
   | <identifier>
   | <string>
<function-type> ::= "[" <function-type-inside> "]"
<function-inside> ::= <function-generic>? <type>+ "->" <type>
<function-generic> ::= "{" <word>+ "}"
<list-type> ::=
   | "(" <type>* ")"
   | "[" <type>* "]"
