## README
#! case insensitive
#! token mode (whitespace omitted between tokens)
#! ordered unions (<a> | <b> is different than <b> | <a>)

<comment> ::= (<meaningful> | <garbage>)*
<garbage> ::= <anything> "\n"
<meaningful> ::=
   | <template>
   | <declaration>
   | <annotation>

<template> ::= "template" ":"? "\n" <declaration>

<declaration> ::= <a> <declaration-target> "is" (<sum-type> | <alias>)
<declaration-target> ::=
   | <word> ("(" <word> ")")?
   | <declaration-generic>
<declaration-generic> ::=
   | "(" <word> <word>+ ")"
   | "[" <word> <word>+ ")"
<sum-type-rhs> ::= "one" "of" <sum-type-element>+
<sum-type-element> ::= "-" <type-expr>
<alias-rhs> ::= <a>? <type-expr>

<type-expr> ::=
   | <list-type>
   | <function-type>
   | <bare-type>
<list-type> ::=
   | "(" <type-expr>* "]"
   | "[" <type-expr>* "]"
<function-type> ::= <generic-param>* <type-expr>* "->" <type-expr>
<generic-param> ::= "{" <word> "}"
<bare-type> ::= <word>

<word> ::= assumed
<a> ::= "a" | "an"
